apiVersion: v1
kind: PersistentVolume
metadata:
  name: cosy-voice-pv
  labels:
    app: cosy-voice
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/cosy-voice-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosy-voice-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: cosy-voice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosy-voice-gradio
  namespace: default
  labels:
    app: cosy-voice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosy-voice
  template:
    metadata:
      labels:
        app: cosy-voice
    spec:
      containers:
      - name: cosy-voice-gradio
        image: harbor.zipsa-lab.com/library/cosy-voice-gradio:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7860
          name: gradio
          protocol: TCP
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: cosy-voice-storage
          mountPath: /app/data
        - name: model-cache
          mountPath: /root/.cache
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: GRADIO_SERVER_NAME
          value: "0.0.0.0"
        - name: GRADIO_SERVER_PORT
          value: "7860"
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: cosy-voice-storage
        persistentVolumeClaim:
          claimName: cosy-voice-pvc
      - name: model-cache
        emptyDir:
          sizeLimit: 20Gi
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: cosy-voice-service
  namespace: default
  labels:
    app: cosy-voice
spec:
  type: NodePort
  selector:
    app: cosy-voice
  ports:
  - port: 7860
    targetPort: 7860
    nodePort: 30860
    protocol: TCP
    name: gradio
---
apiVersion: v1
kind: Service
metadata:
  name: cosy-voice-lb
  namespace: default
  labels:
    app: cosy-voice
spec:
  type: LoadBalancer
  selector:
    app: cosy-voice
  ports:
  - port: 80
    targetPort: 7860
    protocol: TCP
    name: http