apiVersion: v1
kind: PersistentVolume
metadata:
  name: cosy-voice-pv
  labels:
    app: cosy-voice
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/cosy-voice-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosy-voice-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: cosy-voice